### ISSUE TITLE
ExportDataValidationTests should create and validate its own data

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1033]
**User story**
The ExportDataValidationTests currently export all data in the server. This slows down tests for larger testing databases. The tests should instead insert its own resources (using a tag) and export this limited set for validation

**Acceptance criteria**
1. Export tests only export a subset of data for validation
2. Tests to do slow down on larger databases

**Comment by brandonpollett** [comment]
Also, if you run the `GivenFhirServer_WhenDataIsExported_ThenExportedDataIsSameAsDataInFhirServer` against an empty server it throws an exception
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Health.Fhir.Tests.E2E.Rest.ExportDataValidationTests.GetResourcesFromFhirServer(Uri requestUri) in C:\projects\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\ExportDataValidationTests.cs:line 181
   at Microsoft.Health.Fhir.Tests.E2E.Rest.ExportDataValidationTests.GivenFhirServer_WhenDataIsExported_ThenExportedDataIsSameAsDataInFhirServer() in C:\projects\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\ExportDataValidationTests.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
```
