### ISSUE TITLE
E2E test broken:GivenATransactionBundleWithValidEntries_WhenSuccessfulPost_ThenAuditLogEntriesShouldBeCreated 

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1058]
This test fails locally (the only configuration where it runs):

```
[xUnit.net 00:01:08.49]     Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests(SqlServer, Json).GivenATransactionBundleWithValidEntries_WhenSuccessfulPost_ThenAuditLogEntriesShouldBeCreated [FAIL]
  X Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests(SqlServer, Json).GivenATransactionBundleWithValidEntries_WhenSuccessfulPost_ThenAuditLogEntriesShouldBeCreated [574ms]
  Error Message:
   Assert.Collection() Failure
Collection: [AuditEntry { Action = "transaction", AuditAction = Executing, CallerClaims = [...], CallerIpAddress = null, CorrelationId = "1dcf04fa-452c-4552-84bd-f92a11c46efd", ... }, AuditEntry { Action = "create", AuditAction = Executing, CallerClaims = [...], CallerIpAddress = null, CorrelationId = "1dcf04fa-452c-4552-84bd-f92a11c46efd", ... }, AuditEntry { Action = "create", AuditAction = Executed, CallerClaims = [...], CallerIpAddress = null, CorrelationId = "1dcf04fa-452c-4552-84bd-f92a11c46efd", ... }, AuditEntry { Action = "create", AuditAction = Executing, CallerClaims = [...], CallerIpAddress = null, CorrelationId = "1dcf04fa-452c-4552-84bd-f92a11c46efd", ... }, AuditEntry { Action = "create", AuditAction = Executed, CallerClaims = [...], CallerIpAddress = null, CorrelationId = "1dcf04fa-452c-4552-84bd-f92a11c46efd", ... }, ...]
Error during comparison of item at index 6
Inner exception: Assert.Equal() Failure
        Expected: OK
        Actual:   Created
  Stack Trace:
     at Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests.ValidateAuditEntry(AuditEntry auditEntry, AuditAction expectedAuditAction, String expectedAction, Nullable`1 expectedResourceType, Uri expectedUri, Nullable`1 expectedStatusCode, String expectedCorrelationId, String expectedClaimValue, String expectedClaimKey, Dictionary`2 expectedCustomAuditHeaders) in D:\repos\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\Audit\AuditTests.cs:line 660
   at Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests.ValidateExecutedAuditEntry(AuditEntry auditEntry, String expectedAction, Nullable`1 expectedResourceType, Uri expectedUri, Nullable`1 expectedStatusCode, String expectedCorrelationId, String expectedClaimValue, String expectedClaimKey, Dictionary`2 expectedCustomAuditHeaders) in D:\repos\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\Audit\AuditTests.cs:line 650
   at Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests.<>c__DisplayClass31_1`1.<ExecuteAndValidateBundle>b__1(AuditEntry ae) in D:\repos\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\Audit\AuditTests.cs:line 497
   at Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests.ExecuteAndValidateBundle[T](Func`1 action, List`1 expectedList, String expectedAppId) in D:\repos\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\Audit\AuditTests.cs:line 501
   at Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests.GivenATransactionBundleWithValidEntries_WhenSuccessfulPost_ThenAuditLogEntriesShouldBeCreated() in D:\repos\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\Audit\AuditTests.cs:line 524
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by CaitlinV39** [comment]
AB#76672

**Comment by EXPEkesheth** [comment]
Fix for tests provided and hence closing.
