### ISSUE TITLE
Malformed continuation token results in 500

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1259]
When using SQL Server as the backend, call

``` 
GET https://localhost:44348/Patient?_sort=birthdate&ct=bla
```

result:
```
System.Text.Json.JsonException: 'b' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'b' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Microsoft.Health.Fhir.Core.Features.Search.ContinuationToken.FromString(String json) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Search\ContinuationToken.cs:line 70
   at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchImpl(SearchOptions searchOptions, Boolean historySearch, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\SqlServerSearchService.cs:line 144
   at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchInternalAsync(SearchOptions searchOptions, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\SqlServerSearchService.cs:line 126
   at Microsoft.Health.Fhir.Core.Features.Search.SearchService.SearchAsync(String resourceType, IReadOnlyList`1 queryParameters, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Search\SearchService.cs:line 52
   at Microsoft.Health.Fhir.Core.Features.Search.SearchResourceHandler.Handle(SearchResourceRequest message, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Search\SearchResourceHandler.cs:line 54
   at Microsoft.Health.Fhir.Core.Features.Search.Behavior.ListSearchPipeBehavior.Handle(SearchResourceRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Search\Behaviors\ListSearchPipeBehavior.cs:line 63
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Microsoft.Health.Fhir.Core.Extensions.FhirMediatorExtensions.SearchResourceAsync(IMediator mediator, String type, IReadOnlyList`1 queries, CancellationToken cancellationToken) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Extensions\FhirMediatorExtensions.cs:line 70
   at Microsoft.Health.Fhir.Api.Controllers.FhirController.PerformSearch(String type, IReadOnlyList`1 queries) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Api\Controllers\FhirController.cs:line 485
   at Microsoft.Health.Fhir.Api.Controllers.FhirController.SearchByResourceType(String typeParameter) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Shared.Api\Controllers\FhirController.cs:line 414
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Api.Modules.InitializationModule.<>c__DisplayClass2_0.<<Configure>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextAfterAuthenticationMiddleware.Invoke(HttpContext context, IFhirRequestContextAccessor fhirRequestContextAccessor) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\Context\FhirRequestContextAfterAuthenticationMiddleware.cs:line 36
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextBeforeAuthenticationMiddleware.Invoke(HttpContext context) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\Context\FhirRequestContextBeforeAuthenticationMiddleware.cs:line 45
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 63
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 90
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 52
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Health.Api.Features.Audit.AuditMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Introduced in #1184

**Comment by CaitlinV39** [comment]
AB#76269

**Comment by brendankowitz** [comment]
This is also not handled correctly in cosmosdb:

```
 ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.MalformedContinuationTokenException: Malformed Continuation Token: [{"token":"+RID:~jQ9KAMVp8SB3BQAAAAAAAA==#RT:1#TRC:2#ISV:2#IEO:65551#QCF:1#FPC:AgEAAABgAHEFgBRxARACIoAigAyBEQACHCEAcAbVgB6AJIB7gBIAlQIAcBEAhAGYg
SGAF4BRAAMAeoEjgBmAgYAagCCAToABwAY4b4ABwA8AcgAAwAEAIQAZASGAF4BDAACcAQDgHw==","range":{"min":"","max":"FF"}}]?6
 ---> Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Json.JsonUnexpectedTokenException: Encountered an unexpected JSON token., Windows/10.0.17763 cosmos-netstandard-sdk/3.
11.4
   at Microsoft.Azure.Cosmos.Json.JsonReader.JsonTextReader.Read()
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.Parser.ParseArrayNode(IJsonReader jsonTextReader)
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.Parser.ParseNode(IJsonReader jsonTextReader)
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.Parser.Parse(IJsonReader jsonTextReader)
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.<>c__DisplayClass3_0.<.ctor>g__CreateRootNode|0()
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator..ctor(ReadOnlyMemory`1 buffer)
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.Create(ReadOnlyMemory`1 buffer, IReadOnlyJsonStringDictionary jsonStringDictionary)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.CreateFromBuffer[TCosmosElement](ReadOnlyMemory`1 buffer)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.CreateFromBuffer[TCosmosElement](ReadOnlyMemory`1 buffer)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.Parse[TCosmosElement](String serializedCosmosElement)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.Parse(String serializedCosmosElement)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.Create(CosmosQueryClient client, CosmosClientContext clientContext, SqlQuerySpec sqlQuerySpec, String continuationToken, FeedRangeInternal feedRangeInternal, QueryRequestOptions queryRequestOptions, String resourc
eLink, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean forcePassthrough, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo)
   at Microsoft.Azure.Cosmos.ContainerCore.GetItemQueryStreamIteratorInternal(SqlQuerySpec sqlQuerySpec, Boolean isContinuationExcpected, String continuationToken, FeedRangeInternal feedRange, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerCore.GetItemQueryStreamIterator(QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerInlineCore.GetItemQueryStreamIterator(QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerCore.GetItemQueryIterator[T](QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerInlineCore.GetItemQueryIterator[T](QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
   at Microsoft.Health.Fhir.CosmosDb.Features.Queries.CosmosQueryFactory.Create[T](Container container, CosmosQueryContext context)
   at Microsoft.Health.Fhir.CosmosDb.Features.Storage.CosmosFhirDataStore.ExecuteDocumentQueryAsync[T](QueryDefinition sqlQuerySpec, QueryRequestOptions feedOptions, String continuationToken, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Health.Fhir.CosmosDb.Features.Storage.CosmosFhirDataStore.ExecuteDocumentQueryAsync[T](QueryDefinition sqlQuerySpec, QueryRequestOptions feedOptions, String continuationToken, CancellationToken cancellationToken)
   at Microsoft.Health.Fhir.CosmosDb.Features.Search.FhirCosmosSearchService.ExecuteSearchAsync(QueryDefinition sqlQuerySpec, SearchOptions searchOptions, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

```

**Comment by CaitlinV39** [comment]
@johnstairs can this be closed?

**Comment by johnstairs** [comment]
Closed.
