### ISSUE TITLE
500 when SQL Timeout

### ISSUE THREAD

**Issue by CaitlinV39** [microsoft/fhir-server#1452]
**Describe the bug**
A customer reported that they got a 500 when running a search query, which ended up being a timeout. 

**FHIR Version?**
Stu3 (likely other versions)

**Data provider?**
SQL Server

**To Reproduce**
1. Load 100,000 providers into an S1 SQL FHIR Server
2. Run a search to pull all providers
3. Receive a 500

**Expected behavior**
Ideally you wouldn't receive a timeout but if they do, it shouldn't be a 500

**Actual behavior**
Receive a 500

**Example Trace**

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)

   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)

   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location ---

   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)

   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

   at Microsoft.Health.Fhir.SqlServer.Features.Storage.SqlServerFhirDataStore.UpsertAsync(ResourceWrapper resource, WeakETag weakETag, Boolean allowCreate, Boolean keepHistory, CancellationToken cancellationToken)
```

**Comment by CaitlinV39** [comment]
@johnstairs This was another SQL query example

**Comment by CaitlinV39** [comment]
AB#77508
