### ISSUE TITLE
AnonymizedExportTests fail locally.

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1517]
**Describe the bug**
When running all E2E tests locally, the `AnonymizedExportTests` tests fail.

**FHIR Version?**
All

**Data provider?**
All

**To Reproduce**
Run `dotnet test`

**Expected behavior**
Tests pass

**Actual behavior**
See failures like
```
  Error Message:
   System.Collections.Generic.KeyNotFoundException : The given key 'Microsoft.Health.Fhir.Core.Features.Operations.Export.ExportTaskMetricsNotification' was not present in the dictionary.
  Stack Trace:
     at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.Health.Fhir.Shared.Tests.E2E.Rest.AnonymizedExportTests.GivenInvalidEtagProvided_WhenExportingAnonymizedData_ThenBadRequestShouldBeReturned() in D:\repos\fhir-server\test\Microsoft.Health.Fhir.Shared.Tests.E2E\Rest\AnonymizedExportTests.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by LTA-Thinking** [comment]
Tests now pass locally.
