### ISSUE TITLE
ReindexJobTaskTests UnitTests have intermittent failures

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1619]
**Describe the bug**

When running Unit tests (seen sometimes in CI), these ReindexJobTaskTests occasionally fail

```
[xUnit.net 00:00:25.75]     Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenContinuationToken_WhenExecuted_ThenAdditionalQueryAdded [FAIL]
  X Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenContinuationToken_WhenExecuted_ThenAdditionalQueryAdded [3s 519ms]
  Error Message:
   Assert.Equal() Failure
Expected: 5
Actual:   30
  Stack Trace:
     at Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenContinuationToken_WhenExecuted_ThenAdditionalQueryAdded() in /home/vsts/work/1/s/src/Microsoft.Health.Fhir.Shared.Core.UnitTests/Features/Operations/Reindex/ReindexJobTaskTests.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:29.26]     Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenSupportedParams_WhenExecuted_ThenCorrectSearchIsPerformed [FAIL]
  X Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenSupportedParams_WhenExecuted_ThenCorrectSearchIsPerformed [3s 509ms]
  Error Message:
   Assert.Equal() Failure
Expected: 5
Actual:   35
  Stack Trace:
     at Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenSupportedParams_WhenExecuted_ThenCorrectSearchIsPerformed() in /home/vsts/work/1/s/src/Microsoft.Health.Fhir.Shared.Core.UnitTests/Features/Operations/Reindex/ReindexJobTaskTests.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by Ivanidzo4ka** [comment]
I also see this error:
``` [xUnit.net 00:00:40.65]     Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenNoSupportedParams_WhenExecuted_ThenJobCanceled [FAIL]
  X Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenNoSupportedParams_WhenExecuted_ThenJobCanceled [17s 718ms]
  Error Message:
   Assert.Equal() Failure
Expected: Canceled
Actual:   Failed
  Stack Trace:
     at Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenNoSupportedParams_WhenExecuted_ThenJobCanceled() in D:\a\1\s\src\Microsoft.Health.Fhir.Shared.Core.UnitTests\Features\Operations\Reindex\ReindexJobTaskTests.cs:line 253
--- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:49.23]     Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenRunningJob_WhenExecuted_ThenQueuedQueryCompleted [FAIL]
  X Microsoft.Health.Fhir.Core.UnitTests.Features.Operations.Reindex.ReindexJobTaskTests.GivenRunningJob_WhenExecuted_ThenQueuedQueryCompleted [5s 553ms]
  Error Message:
   NSubstitute.Exceptions.ReceivedCallsException : Expected to receive exactly 2 calls matching:
	SearchForReindexAsync(any IReadOnlyList<Tuple<String, String>>, any String, True, any CancellationToken)
Actually received 9 matching calls:
	SearchForReindexAsync(List<Tuple<String, String>>, "", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "appointmentHash", True, System.Threading.CancellationToken)
	SearchForReindexAsync(List<Tuple<String, String>>, "appointmentResponseHash", True, System.Threading.CancellationToken)
```

**Comment by CaitlinV39** [comment]
AB#79656
