### ISSUE TITLE
FHIR Server tries to write content when status is 204

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1881]
**Describe the bug**
 FHIR Server tries to write content when status is 204.

Log context:
```
Request starting HTTP/1.1 GET https://[server]/_operations/export/[id]

Route matched with {action = "GetExportStatusById", controller = "Export"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] GetExportStatusById(System.String) on controller Microsoft.Health.Fhir.Api.Controllers.ExportController (Microsoft.Health.Fhir.Stu3.Api).

Executing ObjectResult, writing value of type 'Hl7.Fhir.Model.OperationOutcome'.

Executed action Microsoft.Health.Fhir.Api.Controllers.ExportController.GetExportStatusById (Microsoft.Health.Fhir.Stu3.Api) in 16.3687ms

Request finished HTTP/1.1 GET https://[server]/_operations/export/[id] - - - 204 - application/fhir+json;+charset=utf-8 65.3603ms
```

```
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 204.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowWritingToResponseBodyNotSupported()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsyncInternal(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Flush()
   at Microsoft.Health.Fhir.Api.Features.Formatters.FhirJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Api.Modules.InitializationModule.<>c__DisplayClass2_0.<<Configure>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Health.Fhir.Api.Features.Throttling.ThrottlingMiddleware.RunRequest(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Throttling.ThrottlingMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Routing.SearchPostReroutingMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextAfterAuthenticationMiddleware.Invoke(HttpContext context, IFhirRequestContextAccessor fhirRequestContextAccessor)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextBeforeAuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next)
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next)
   at Microsoft.Health.Fhir.Cloud.FhirService.Features.Metrics.RequestMetricForwardingMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in C:\a\1\s\src\FhirApplication\FhirService.Core\Features\Metrics\RequestMetricForwardingMiddleware.cs:line 90
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Health.Api.Features.Audit.AuditMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.ExceptionNotifications.ExceptionNotificationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.ExceptionNotifications.ExceptionNotificationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**Comment by brendankowitz** [comment]
Closing for now, I haven't seen this for a while
