### ISSUE TITLE
First call failing after 7 to 10 SQL Server migration 

### ISSUE THREAD

**Issue by giacomodeliberali** [microsoft/fhir-server#1984]
**Describe the bug**
After migrating our SQL Server schema from 7 to 10, the first (and only the first) api call fails with the following exception:

```
{
    "resourceType": "OperationOutcome",
    "id": "eff35853-2f81-4d13-ba5a-1475af797cac",
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "diagnostics": "There was an error processing your request."
        }
    ]
}
```

```
Hosting environment: Production
Content root path: C:\...\Fhir
Now listening on: http://*:5000/
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The current schema version should not be null.
         at Microsoft.Health.Fhir.SqlServer.Features.Storage.SqlServerFhirModel.ThrowIfCurrentSchemaVersionIsNull() in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\SqlServerFhirModel.cs:line 470
         at Microsoft.Health.Fhir.SqlServer.Features.Storage.SqlServerFhirModel.EnsureInitialized() in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\SqlServerFhirModel.cs:line 176
         at Microsoft.Health.Api.Modules.InitializationModule.<>c__DisplayClass2_0.<<Configure>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.Health.Fhir.Api.Features.Throttling.ThrottlingMiddleware.Invoke(HttpContext context) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\Throttling\ThrottlingMiddleware.cs:line 136
         at Microsoft.Health.Fhir.Api.Features.Routing.SearchPostReroutingMiddleware.Invoke(HttpContext context) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\Routing\SearchPostReroutingMiddleware.cs:line 57
         at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextAfterAuthenticationMiddleware.Invoke(HttpContext context, RequestContextAccessor`1 fhirRequestContextAccessor) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\Context\FhirRequestContextAfterAuthenticationMiddleware.cs:line 37
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextBeforeAuthenticationMiddleware.Invoke(HttpContext context) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\Context\FhirRequestContextBeforeAuthenticationMiddleware.cs:line 46
         at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 64
         at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 90
         at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 53
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.Health.Api.Features.Audit.AuditMiddleware.Invoke(HttpContext context)
         at Microsoft.Health.Fhir.Api.Features.ExceptionNotifications.ExceptionNotificationMiddleware.Invoke(HttpContext context) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\ExceptionNotifications\ExceptionNotificationMiddleware.cs:line 49
         at Microsoft.Health.Fhir.Api.Features.ExceptionNotifications.ExceptionNotificationMiddleware.Invoke(HttpContext context) in D:\a\1\s\uno-ins-fhir-server\src\Microsoft.Health.Fhir.Api\Features\ExceptionNotifications\ExceptionNotificationMiddleware.cs:line 84
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Host under IIS
2. Stop the pool
3. Start the pool
4. Make any request

**Expected behavior**
The first call should not fail (subsequent calls work as expected).

**Actual behavior**
The first call after the fhir server is started fails.

**Comment by CaitlinV39** [comment]
@rbans96 can you look into this?

**Comment by rbans96** [comment]
@giacomodeliberali  Did you perform the schema migration using schema tool or service on the startup itself. Is the request made to fhir-server after schema migration is completed? What is the request you made?

Since I tried to repro this issue on my local by migrating schema from 7 to 10 using tool or service on startup and each request(POST /Patient) is success.

**Comment by giacomodeliberali** [comment]
Actually we created the database at version 4, and we manually (with our own deploy pipeline) applied the `.diff.sql` up to 10. The request is made after the migration is succesful and complete. Tthe error happens with any request on any resource, either GET or POST. The request that we tried was a simple GET `Observation?_sort=-date`.

**Comment by CaitlinV39** [comment]
@giacomodeliberali - Unfortunately we aren't able to produce given that you manually upgraded between the versions. I'm going to close for now as we cannot reproduce but if you have more details or other questions please let us know.
