### ISSUE TITLE
Include doesn't check type of search parameter

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#2003]
**Describe the bug**
Expression parser doesn't check what search parameter is used for include, which leads to 500.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Search Patient?_include=Patient:family
2. Search Patient?_revinclude=Coverage:identifier

**Expected behavior**
Either operation bad request or operation outcome which indicate what such include is not supported.

**Actual behavior**
```
System.ArgumentNullException: Value can not be null. (Parameter 'resourceId')
   at EnsureThat.Enforcers.AnyArg.IsNotNull[T](T value, String paramName, OptsFn optsFn)
   at EnsureThat.Enforcers.StringArg.IsNotNullOrWhiteSpace(String value, String paramName, OptsFn optsFn)
   at Microsoft.Health.Fhir.CosmosDb.Features.Storage.ResourceTypeAndId..ctor(String resourceTypeName, String resourceId) in D:\src\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Features\Storage\ResourceTypeAndId.cs:line 21
```

[AB#102855](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/102855)

**Comment by CaitlinV39** [comment]
AB#82654

**Comment by EXPEkesheth** [comment]
Reopening the issue , as the change was reverted.

**Comment by v-kulkarnipa** [comment]
We have tested whether given search urls are working on Gen1 and Gen2 or not.  We are getting 400 bad request error in response, which is an expected result as mentioned in acceptance criteria.
