### ISSUE TITLE
Posting a Bundle with incorrect Media Type returns a 500

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#2148]
**Describe the bug**
Posting a Bundle with incorrect Media Type returns a 500.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB

**To Reproduce**
 
```
Request starting HTTP/1.1 POST https://***.azurehealthcareapis.com/ application/x-www-form-urlencoded 14

Route matched with {action = "BatchAndTransactions", controller = "Fhir"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] BatchAndTransactions(Hl7.Fhir.Model.Resource) on controller Microsoft.Health.Fhir.Api.Controllers.FhirController (Microsoft.Health.Fhir.R4.Api).

System.ArgumentException: The key '  "entry": [ {' is invalid JQuery syntax because it is missing a closing bracket. (Parameter 'key')
   at Microsoft.AspNetCore.Mvc.ModelBinding.JQueryKeyValuePairNormalizer.NormalizeJQueryToMvc(StringBuilder builder, String key)
   at Microsoft.AspNetCore.Mvc.ModelBinding.JQueryKeyValuePairNormalizer.GetValues(IEnumerable`1 originalValues, Int32 valueCount)
   at Microsoft.AspNetCore.Mvc.ModelBinding.JQueryFormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.TryCreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Api.Modules.InitializationModule.<>c__DisplayClass2_0.<<Configure>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Health.Fhir.Api.Features.Throttling.ThrottlingMiddleware.RunRequest(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Throttling.ThrottlingMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Routing.SearchPostReroutingMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextAfterAuthenticationMiddleware.Invoke(HttpContext context, RequestContextAccessor`1 fhirRequestContextAccessor)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextBeforeAuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next)
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next)
   at Microsoft.Health.Fhir.Cloud.FhirService.Features.Metrics.RequestMetricForwardingMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in D:\a\_work\1\s\src\FhirApplication\FhirService.Core\Features\Metrics\RequestMetricForwardingMiddleware.cs:line 52
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Health.Api.Features.Audit.AuditMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.ExceptionNotifications.ExceptionNotificationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.ExceptionNotifications.ExceptionNotificationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

Executing ObjectResult, writing value of type 'Hl7.Fhir.Model.OperationOutcome'.

Request finished in 43.7477ms 500 application/fhir+json; charset=utf-8

```

**Comment by CaitlinV39** [comment]
AB#84435
