### ISSUE TITLE
Deploying FHIR server in Azure with convert data flag enabled gives SQL error

### ISSUE THREAD

**Issue by sushil-clearsense** [microsoft/fhir-server#2493]
**Describe the bug**
I am trying to deploy the FHIR server in Azure using this template - 
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2Ffhir-server%2Fmain%2Fsamples%2Ftemplates%2Fdefault-azuredeploy-docker.json

These are the settings I am using in the template:
![image](https://user-images.githubusercontent.com/93955508/154739171-f530bcea-eaf6-4209-9daa-f5e13900b25b.png)

The deployment gets completed but the application never gets up. It throws the following error:

`
Error from SQL database on upserting InstanceSchema information
2022-02-18T18:16:04.793236444Z       Microsoft.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'dbo.UpsertInstanceSchema'.
2022-02-18T18:16:04.793246144Z          at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2022-02-18T18:16:04.799508507Z          at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2022-02-18T18:16:04.799518707Z          at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2022-02-18T18:16:04.799522707Z          at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2022-02-18T18:16:04.799526907Z          at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
2022-02-18T18:16:04.799530407Z          at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
2022-02-18T18:16:04.801369766Z          at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
2022-02-18T18:16:04.801381666Z          at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
2022-02-18T18:16:04.801385766Z          at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
2022-02-18T18:16:04.801390566Z          at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
2022-02-18T18:16:04.801500464Z          at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
2022-02-18T18:16:04.801504863Z          at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsyncCallback(IAsyncResult asyncResult)
2022-02-18T18:16:04.801512663Z          at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean
 `

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Use the Azure template in this page to deploy the FHIR server in Azure - https://github.com/Microsoft/fhir-server/blob/main/docs/DefaultDeployment.md
2. Choose config settings for SQL Server and Convert Data flag enabled
3. Check the application logs

**Expected behavior**
The app should be up and running 

**Actual behavior**
App throws SQL exception

Note: When I deploy this app without the convert data flag, i do not see this error in the logs

Log File:
[2022_02_18_lw1sdlwk0000EQ_default_docker.log](https://github.com/microsoft/fhir-server/files/8099596/2022_02_18_lw1sdlwk0000EQ_default_docker.log)

**Comment by sushil-clearsense** [comment]
Any updates on this guys?

**Comment by moria97** [comment]
hi @sushil-clearsense , seems the `Sql Schema Automic Updates Enabled` is set to `tool` which means the sql schema will not be initialized or upgraded on the server startup. The schema migration tool will be required to perform initialize or upgrade. If you set to 'auto', sql schema will be upgraded to the maximum supported version.

See the [Schema Migration Tool] for reference
