### ISSUE TITLE
FHIR R5 v5.0.0-snapshot1 Version Input String Not in Correct Format

### ISSUE THREAD

**Issue by mundij01** [microsoft/fhir-server#2506]
**Describe the bug**
 I've been trying to build and run the Microsoft FHIR Server R5 with the latest published FHIR version (5.0.0-snapshot1.)  I have updated the HL7.FHIR nuget packages to v3.8.0 and successfully built the solution; but I get an exception in VersionSpecificModelInfoProvider.SupportedVersion property initialization: System.FormatException: 'Input string was not in a correct format.'

The code expects the published FHIR version to be in the format x.y.z where x=major, y=minor, z=build and expects all integers. Should the code be updated to accept a suffix to the build integer?

**FHIR Version?**
R5 latest

**Data provider?**
SQL Server

**Comment by brendankowitz** [comment]
This failure is also occurring in #2420. Might need further analysis, but I believe the code only requires the x.y.z parts and should be updated to only use this

**Comment by mundij01** [comment]
One approach could be supporting [Semantic Versioning 2.0.0](https://semver.org/) by changing the type of VersionSpecificModelInfoProvider.SupportedVersion from System.Version to Nuget.Versioning.SemanticVersion.  I'm sure this won't be the last time pre-release FHIR builds will have a suffix.

**Comment by brendankowitz** [comment]
This is just the first exception, in looking into this more the changes for required for 5.0.0-snapshot1 go a lot deeper and needs more code/test changes.

**Comment by mundij01** [comment]
Yes, there are several breaking changes between 4.6.0 and 5.0.0-snapshot1, so test data will need to be recreated.  

Also, I was running into an exception just trying to get capability statement.  Exception mentions "CatalogEntry" but that resource was removed between 4.6.0 and 5.0.0-snapshot1 and don't know why specification.zip has it in there.  (I'm new to a lot of this.)  Here's the exception I got:

```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Metadata", controller = "Fhir"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Metadata() on controller Microsoft.Health.Fhir.Api.Controllers.FhirController (Microsoft.Health.Fhir.R5.Api).
info: Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware[0]
      ApiNotificationMiddleware executed in 00:00:02.2906219.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 HEAD https://localhost:44348/metadata?_format=json&_pretty=true - - - 404 - - 2367.6537ms
fail: Microsoft.Health.Fhir.Api.Features.Filters.OperationOutcomeExceptionFilterAttribute[0]
      InternalServerError error returned
      System.ArgumentException: Unknown resource type CatalogEntry (Parameter 'resourceType')
         at EnsureThat.Enforcers.BoolArg.IsTrue(Boolean value, String paramName, OptsFn optsFn)
         at EnsureThat.EnsureArg.IsTrue(Boolean value, String paramName, OptsFn optsFn)
         at Microsoft.Health.Fhir.Core.Features.Conformance.CapabilityStatementBuilder.ApplyToResource(String resourceType, Action`1 action) in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Conformance\CapabilityStatementBuilder.cs:line 95
         at Microsoft.Health.Fhir.Core.Features.Conformance.CapabilityStatementBuilder.SyncSearchParams(String resourceType) in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Conformance\CapabilityStatementBuilder.cs:line 220
         at Microsoft.Health.Fhir.Core.Features.Conformance.CapabilityStatementBuilder.SyncSearchParameters() in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Conformance\CapabilityStatementBuilder.cs:line 332
         at Microsoft.Health.Fhir.CosmosDb.Features.Storage.CosmosFhirDataStore.Build(ICapabilityStatementBuilder builder) in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Features\Storage\CosmosFhirDataStore.cs:line 550
         at Microsoft.Health.Fhir.Core.Features.Conformance.SystemConformanceProvider.GetCapabilityStatementOnStartup(CancellationToken cancellationToken) in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Conformance\SystemConformanceProvider.cs:line 76
         at Microsoft.Health.Fhir.Api.Features.Formatters.FormatParametersValidator.IsFormatSupportedAsync(ResourceFormat resourceFormat) in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.Shared.Api\Features\Formatters\FormatParametersValidator.cs:line 131
         at Microsoft.Health.Fhir.Api.Features.Formatters.FormatParametersValidator.CheckRequestedContentTypeAsync(HttpContext httpContext) in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.Shared.Api\Features\Formatters\FormatParametersValidator.cs:line 60
         at Microsoft.Health.Fhir.Api.Features.Filters.ValidateFormatParametersAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in C:\Users\mundij01\source\training\fhir-server\src\Microsoft.Health.Fhir.Api\Features\Filters\ValidateFormatParametersAttribute.cs:line 43
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Hl7.Fhir.Model.OperationOutcome'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Microsoft.Health.Fhir.Api.Controllers.FhirController.Metadata (Microsoft.Health.Fhir.R5.Api) in 785.4157ms
info: Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware[0]
      ApiNotificationMiddleware executed in 00:00:03.1085201.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:44348/metadata?_format=json&_pretty=true - - - 500 - application/fhir+xml;+charset=utf-8 3166.8131ms
```

**Comment by brendankowitz** [comment]
@mundij01 correct, as R5 iterates its likely data in test servers will become invalid
