### ISSUE TITLE
SMART Launcher example doesn't seem to work

### ISSUE THREAD

**Issue by bruceharrison1984** [microsoft/fhir-server#2511]
**Describe the bug**
Setting up FHIR w/Proxy according to [Tutorial: Azure Active Directory SMART on FHIR proxy](https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/use-smart-on-fhir-proxy) and using the [SMART Launcher sample](https://github.com/microsoft/fhir-server/tree/main/samples/apps/SmartLauncher) from this repo doesn't work.

**To Reproduce**
Once configured, filling out the initial launch page in the sample and attempting to login, I get a 401, `The request body must contain the following parameter: 'client_assertion' or 'client_secret'.` error in the browser console. My App Registration is set to `public`, and setting up my own test project it seems to work if I set the `iss` or `fhirServiceUrl` property during authorization.

However, I still am not receiving any additional claims via launch properties.

**Expected behavior**
Login succeeds and claims are displayed

**Actual behavior**
The authorization call fails

**Comment by bruceharrison1984** [comment]
To add some more detail here, I just don't understand how this is supposed to work.

Calling the authorize endpoint via `fhirclient` with the a concrete redirect uri *and* a `client_secret` returns a tokenResponse object:
```js
SMART.authorize({
  redirectUri: 'http://localhost:3000/smart',
  iss: issuer,
  clientId: process.env.REACT_APP_CLIENT_ID as string,
  clientSecret: process.env.REACT_APP_CLIENT_SECRET as string,
  scope: 'openid profile',
});

/* token */
{
  "clientId": "1255c8d0-xxxx-xxxx-xxxx-6e39bca8addb",
  "scope": "openid profile",
  "redirectUri": "http://localhost:3000/smart",
  "serverUrl": "https://xxxxx.azurehealthcareapis.com",
  "clientSecret": "rdc7Q~...",
  "tokenResponse": {
      "token_type": "Bearer",
      "scope": "user_impersonation",
      "expires_in": "4910",
      "ext_expires_in": "4910",
      "expires_on": "1647022495",
      "not_before": "1647017284",
      "resource": "https://xxxxx.azurehealthcareapis.com",
      "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOi...",
      "refresh_token": "0.AUUA17Zbd6oB00SPjjiba6...",
      "id_token": "eyJ0eXAiOiJKV1QiLC...",
      "client_id": "1255c8d0-xxxx-xxxx-xxxx-6e39bca8addb"
  },
  "key": "PguvjX1CoGiWfo6r",
  "registrationUri": "",
  "authorizeUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/authorize",
  "tokenUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/token",
  "expiresAt": "16470175844910"
}
```

Calling authorize *without* a `client_secret` and _despite the App Registration being public_ fails to authenticate:
```js
SMART.authorize({
  redirectUri: 'http://localhost:3000/smart',
  iss: issuer,
  clientId: process.env.REACT_APP_CLIENT_ID as string,
  scope: 'openid profile',
});

/* console error */
lib.js:106 Uncaught (in promise) HttpError: 401 
URL: https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/token
invalid_client: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 26c7144e-8668-40c1-8ce1-7e5b2dfd3000
Correlation ID: 524bc79c-c1af-4003-b499-9698230526b3
Timestamp: 2022-03-11 16:57:38Z
    at checkResponse (lib.js:106:1)
    at async completeAuth (smart.js:566:1)
```

I would fully expect this to work and not need a `client_secret`, since requiring one completely invalidates many use cases.

Finally, attempting to send the payload specified in these [Azure Active Directory SMART on FHIR proxy docs](https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/use-smart-on-fhir-proxy?WT.mc_id=Portal-Microsoft_Healthcare_APIs) returns a payload, but it is completely useless. It doesn't need a `client_secret` though.

```js
/* launch payload */
{ "patient" : 1 }

SMART.authorize({
  redirectUri: 'http://localhost:3000/smart?launch=eyJwYXRpZW50IjoiMTIzNDUifQ%3D%3D&iss=https%3A%2F%2Fxxxxx.azurehealthcareapis.com',
  iss: issuer,
  clientId: process.env.REACT_APP_CLIENT_ID as string,
  scope: 'openid profile',
});

/* Redirect URI */
`https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/callback/aHR0cDovL2xvY2FsaG9zdDozMDAwL3NtYXJ0P2xhdW5jaD1leUp3WVhScFpXNTBJam9pTVRJek5EVWlmUSUzRCUzRCZpc3M9aHR0cHMlM0ElMkYlMkZwcmltZXRzcjEuYXp1cmVoZWFsdGhjYXJlYXBpcy5jb20`

/* Response Token from SMART Proxy */
{
  "clientId": "1255c8d0-xxxx-xxxx-xxxx-6e39bca8addb",
  "scope": "openid profile",
  "redirectUri": "http://localhost:3000/smart?launch=eyJwYXRpZW50IjoiMTIzNDUifQ%3D%3D&iss=https%3A%2F%2Fxxxxx.azurehealthcareapis.com",
  "serverUrl": "https://xxxxx.azurehealthcareapis.com",
  "clientSecret": "rdc7Q~X...",
  "tokenResponse": {},
  "key": "FkTvp7Rz11dfjuN5",
  "registrationUri": "",
  "authorizeUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/authorize",
  "tokenUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/token"
}
```
The returned payload is essentially useless, containing no access or ID tokens, nor the patient claim that should have been attached.

A further problem with this last example is that anytime the launch parameters(patient) change, it requires adding the new redirect uri to the App Registration because the `AadSmartOnFhirProxy` callback is some kind of hash of the launch parameters and the iss parameter. How exactly is this supposed to work?

**Comment by bruceharrison1984** [comment]
Closed for https://github.com/microsoft/fhir-server/issues/2512
