### ISSUE TITLE
AadSmartOnFhirProxy proper usage?

### ISSUE THREAD

**Issue by bruceharrison1984** [microsoft/fhir-server#2512]
**Describe the bug**
I just don't understand how this is supposed to work. I'm going to run-off the couple of scenarios I ran though while trying to get this working.

Calling the authorize endpoint via `fhirclient` with a concrete redirect uri *and* a `client_secret` returns a tokenResponse object (as expected):
```js
/* issuer: https://xxxx.azurehealthcareapis.com */

SMART.authorize({
  redirectUri: 'http://localhost:3000/smart',
  iss: issuer,
  clientId: process.env.REACT_APP_CLIENT_ID as string,
  clientSecret: process.env.REACT_APP_CLIENT_SECRET as string,
  scope: 'openid profile',
});

/* token */
{
  "clientId": "1255c8d0-xxxx-xxxx-xxxx-6e39bca8addb",
  "scope": "openid profile",
  "redirectUri": "http://localhost:3000/smart",
  "serverUrl": "https://xxxxx.azurehealthcareapis.com",
  "clientSecret": "rdc7Q~...",
  "tokenResponse": {
      "token_type": "Bearer",
      "scope": "user_impersonation",
      "expires_in": "4910",
      "ext_expires_in": "4910",
      "expires_on": "1647022495",
      "not_before": "1647017284",
      "resource": "https://xxxxx.azurehealthcareapis.com",
      "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOi...",
      "refresh_token": "0.AUUA17Zbd6oB00SPjjiba6...",
      "id_token": "eyJ0eXAiOiJKV1QiLC...",
      "client_id": "1255c8d0-xxxx-xxxx-xxxx-6e39bca8addb"
  },
  "key": "PguvjX1CoGiWfo6r",
  "registrationUri": "",
  "authorizeUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/authorize",
  "tokenUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/token",
  "expiresAt": "16470175844910"
}
```

Calling authorize *without* a `client_secret` and **despite the App Registration being public** fails to authenticate:
```js
SMART.authorize({
  redirectUri: 'http://localhost:3000/smart',
  iss: issuer,
  clientId: process.env.REACT_APP_CLIENT_ID as string,
  scope: 'openid profile',
});

/* console error */
lib.js:106 Uncaught (in promise) HttpError: 401 
URL: https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/token
invalid_client: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 26c7144e-8668-40c1-8ce1-7e5b2dfd3000
Correlation ID: 524bc79c-c1af-4003-b499-9698230526b3
Timestamp: 2022-03-11 16:57:38Z
    at checkResponse (lib.js:106:1)
    at async completeAuth (smart.js:566:1)
```

I would fully expect this to work and not need a `client_secret`, since requiring one completely invalidates many use cases.

Finally, attempting to send the payload specified in these [Azure Active Directory SMART on FHIR proxy docs](https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/use-smart-on-fhir-proxy?WT.mc_id=Portal-Microsoft_Healthcare_APIs) returns a payload, but it is completely useless. Supplying a `client_secret` doesn't matter, it simply echos the value back in the response even if it is the incorrect `client_secret`. Not supplying one just omits that value from the response.

```js
/* launch payload */
{ "patient" : 1 }

SMART.authorize({
  redirectUri: 'http://localhost:3000/smart?launch=eyJwYXRpZW50IjoiMTIzNDUifQ%3D%3D&iss=https%3A%2F%2Fxxxxx.azurehealthcareapis.com',
  iss: issuer,
  clientId: process.env.REACT_APP_CLIENT_ID as string,
  clientSecret: 'incorrect-value',
  scope: 'openid profile',
});

/* Redirect URI */
`https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/callback/aHR0cDovL2xvY2FsaG9zdDozMDAwL3NtYXJ0P2xhdW5jaD1leUp3WVhScFpXNTBJam9pTVRJek5EVWlmUSUzRCUzRCZpc3M9aHR0cHMlM0ElMkYlMkZwcmltZXRzcjEuYXp1cmVoZWFsdGhjYXJlYXBpcy5jb20`

/* Response Token from SMART Proxy */
{
  "clientId": "1255c8d0-xxxx-xxxx-xxxx-6e39bca8addb",
  "scope": "openid profile",
  "redirectUri": "http://localhost:3000/smart?launch=eyJwYXRpZW50IjoiMTIzNDUifQ%3D%3D&iss=https%3A%2F%2Fxxxxx.azurehealthcareapis.com",
  "serverUrl": "https://xxxxx.azurehealthcareapis.com",
  "clientSecret": "incorrect-value",
  "tokenResponse": {},
  "key": "FkTvp7Rz11dfjuN5",
  "registrationUri": "",
  "authorizeUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/authorize",
  "tokenUri": "https://xxxxx.azurehealthcareapis.com/AadSmartOnFhirProxy/token"
}
```
The returned payload is essentially useless, containing no access or ID tokens, nor the patient claim that should have been attached.

A further problem with this last example is that anytime the launch parameters(patient) change, **it requires adding the new redirect uri to the App Registration**. This is because the `AadSmartOnFhirProxy` callback is unique to the combination of launch parameters and the iss parameter, and it changes whenever the launch value changes. 

This is clearly not feasible for a variety of reasons, primarily there is a limit to the number of redirect urls, and there is a character limit on the redirect urls. Using a GUID as a patient ID as Azure FHIR does immediately violates this callback character limit. That skips over adding a new redirect url for each possible value is just not feasible anyway.

I modeled my react-based test app off of [the one in this repo](https://github.com/microsoft/fhir-server/tree/main/samples/apps/SmartLauncher), which OOTB doesn't appear to work correctly either. It suffers from the second scenario I laid out.

How exactly is `AadSmartOnFhirProxy` supposed to work? I am doing this completely wrong? The documentation around this feature seems to be limited to the single page noted above, and a single example app in this repo that doesn't seem to work properly either.

**Data provider?**
Azure FHIR

**Comment by bruceharrison1984** [comment]
Re-opening. My application works f
