### ISSUE TITLE
Error while perform create operation  on latest version 

### ISSUE THREAD

**Issue by shuhaibk54** [microsoft/fhir-server#3012]
I am getting the below error when I try to post the bundle. Interestingly all search functionality works fine.

**Message: Unable to resolve service for type 'Microsoft.Health.Fhir.Core.Features.Search.IDataStoreSearchParameterValidator' while attempting to activate 'Microsoft.Health.Fhir.Core.Features.Search.Parameters.SearchParameterOperations'.**

**source: Microsoft.Extensions.DependencyInjection** 

stack trace :    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at MediatR.ServiceFactoryExtensions.GetInstances[T](ServiceFactory factory)
   at MediatR.Wrappers.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, ServiceFactory serviceFactory, CancellationToken cancellationToken)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Microsoft.Health.Fhir.Core.Extensions.FhirMediatorExtensions.<CreateResourceAsync>d__0.MoveNext() in E:\Workspaces\Shuhaib\FHIR\fhir-server-main\src\Microsoft.Health.Fhir.Shared.Core\Extensions\FhirMediatorExtensions.cs:line 34
   at Microsoft.Health.Fhir.Api.Controllers.FhirController.<Create>d__6.MoveNext() in E:\Workspaces\Shuhaib\FHIR\fhir-server-main\src\Microsoft.Health.Fhir.Shared.Api\Controllers\FhirController.cs:line 159

**Comment by brendankowitz** [comment]
@rajithaalurims can you take a look?

**Comment by rajithaalurims** [comment]
I am taking a look.

**Comment by shuhaibk54** [comment]
> I am taking a look.

thanks

**Comment by rajithaalurims** [comment]
@shuhaibk54  
Sorry for the delay in reply. I cannot reproduce the behavior. 
Can you share the sample bundle you are trying? 
Can you also confirm the build id you are running this on?

Thanks.

**Comment by EXPEkesheth** [comment]
@shuhaibk54 Do you have additional information requested? This issue will closed after a week, if no response received.

**Comment by EXPEkesheth** [comment]
Closing issue as there is no response..
