### ISSUE TITLE
FhirTimer crashes the process on shutdown

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#3736]
**Describe the bug**

FhirTimer crashes the process on shutdown.

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Health.Fhir.SqlServer.Features.Watchdogs.FhirTimer`1.RunInternalAsync() in /_/src/Microsoft.Health.Fhir.SqlServer/Features/Watchdogs/FhirTimer.cs:line 61
   at Microsoft.Health.Fhir.SqlServer.Features.Watchdogs.FhirTimer`1.<StartAsync>b__25_0(Object _) in /_/src/Microsoft.Health.Fhir.SqlServer/Features/Watchdogs/FhirTimer.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart(
```

**FHIR Version?**
All

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Run an e2e test in debug
2. When test ends process crashes

**Comment by EXPEkesheth** [comment]
Closing as addressed with PR [#4666](https://github.com/microsoft/fhir-server/pull/4666)
