### ISSUE TITLE
System.OutOfMemoryException thrown when attempting to export large set of data.

### ISSUE THREAD

**Issue by rafalbroll-datapharm** [microsoft/fhir-server#3755]
**Describe the bug**
The export operation is failing with the exception `System.OutOfMemoryException`. Although the dataset is quite big, a single row is 5 KB at max, so with the right strategy of data-chunking, the export operation shouldn't run out of memory.

The command used to initiate the export:
`<fhir server url>/$export?_container=$containerName&_since=$YesterdayDate&_till=$CurrentDate&_type=MedicinalProductDefinition,Bundle,Composition,Ingredient,Organization,RegulatedAuthorization,SubstanceDefinition
    `

**Hosting details:**
The FHIR Server is hosted inside the Azure Container App, with assigned resources: 
`1 CPU, 2 GB RAM`
The export is targeted to the Azure Storage Account

**The data instance sizes:**
The entire Resources table is ~60 GB, 978 676 rows
The biggest Resource row (measured as `datalength(rawresource)`) is 5 MB, average is 58 KB

**The stacktrace is:**
```
fail: Microsoft.Health.Fhir.Core.Features.Operations.Export.ExportJobTask[0]
      Encountered an unhandled exception. The job will be marked as failed.
      System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
         at System.Text.StringBuilder.ToString()
at Microsoft.Health.Fhir.SqlServer.Features.Storage.CompressedRawResourceConverter.ReadCompressedRawResource(Stream compressedResourceStream) in /repo/src/Microsoft.Health.Fhir.SqlServer/Features/Storage/CompressedRawResourceConverter.cs:line 35
at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.<>c__DisplayClass23_0.<<SearchImpl>b__0>d.MoveNext() in /repo/src/Microsoft.Health.Fhir.SqlServer/Features/Search/SqlServerSearchService.cs:line 536
      --- End of stack trace from previous location ---
at Microsoft.Health.Fhir.SqlServer.Features.Storage.SqlRetryService.ExecuteSql(Func`3 action, CancellationToken cancellationToken) in /repo/src/Microsoft.Health.Fhir.SqlServer/Features/Storage/SqlRetry/SqlRetryService.cs:line 227
at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchImpl(SqlSearchOptions sqlSearchOptions, SqlSearchType searchType, String currentSearchParameterHash, CancellationToken cancellationToken) in /repo/src/Microsoft.Health.Fhir.SqlServer/Features/Search/SqlServerSearchService.cs:line 539
at Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService.SearchAsync(SearchOptions searchOptions, CancellationToken cancellationToken) in /repo/src/Microsoft.Health.Fhir.SqlServer/Features/Search/SqlServerSearchService.cs:line 204
at Microsoft.Health.Fhir.Core.Features.Search.SearchService.SearchAsync(String resourceType, IReadOnlyList`1 queryParameters, CancellationToken cancellationToken, Boolean isAsyncOperation, ResourceVersionType resourceVersionTypes) in /repo/src/Microsoft.Health.Fhir.Core/Features/Search/SearchService.cs:line 54
at Microsoft.Health.Fhir.Core.Features.Operations.Export.ExportJobTask.SearchWithFilter(ExportJobConfiguration exportJobConfiguration, ExportJobProgress progress, String resourceType, List`1 queryParametersList, List`1 sharedQueryParametersList, ResourceVersionType resourceVersionTypes, IAnonymizer anonymizer, CancellationToken cancellationToken) in /repo/src/Microsoft.Health.Fhir.Core/Features/Operations/Export/ExportJobTask.cs:line 475
at Microsoft.Health.Fhir.Core.Features.Operations.Export.ExportJobTask.RunExportSearch(ExportJobConfiguration exportJobConfiguration, ExportJobProgress progress, List`1 sharedQueryParametersList, ResourceVersionType resourceVersionTypes, CancellationToken cancellationToken) in /repo/src/Microsoft.Health.Fhir.Core/Features/Operations/Export/ExportJobTask.cs:line 428
at Microsoft.Health.Fhir.Core.Features.Operations.Export.ExportJobTask.ExecuteAsync(ExportJobRecord exportJobRecord, WeakETag weakETag, CancellationToken cancellationToken) in /repo/src/Microsoft.Health.Fhir.Core/Features/Operations/Export/ExportJobTask.cs:line 291
fail: Microsoft.Health.JobManagement.JobHosting[0]
Job with id: 78 and group id: 75 of type: 1 failed.
      Microsoft.Health.JobManagement.JobExecutionException: Unknown Error.
at Microsoft.Health.Fhir.Core.Features.Operations.Export.ExportProcessingJob.<>c__DisplayClass3_0.<ExecuteAsync>b__0(Task parent) in /repo/src/Microsoft.Health.Fhir.Core/Features/Operations/Export/ExportProcessingJob.cs:line 64
at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
at Microsoft.Health.JobManagement.JobHosting.ExecuteJobWithHeartbeatsAsync(IQueueClient queueClient, Byte queueType, Int64 jobId, Int64 version, Func`2 action, TimeSpan heartbeatPeriod, CancellationTokenSource cancellationTokenSource) in /repo/src/Microsoft.Health.TaskManagement/JobHosting.cs:line 218
at Microsoft.Health.JobManagement.JobHosting.ExecuteJobWithHeartbeatsAsync(IQueueClient queueClient, Byte queueType, Int64 jobId, Int64 version, Func`2 action, TimeSpan heartbeatPeriod, CancellationTokenSource cancellationTokenSource) in /repo/src/Microsoft.Health.TaskManagement/JobHosting.cs:line 218
at Microsoft.Health.JobManagement.JobHosting.ExecuteJobAsync(JobInfo jobInfo, Boolean useHeavyHeartbeats) in /repo/src/Microsoft.Health.TaskManagement/JobHosting.cs:line 205
```

**FHIR Version?**
R4B, [3.4.342]

**Data provider?**
SQL Server

**To Reproduce**
Steps to reproduce the behaviour:
1. Prepare the data set of similar size. The entities used in failing scenario are:
- MedicinalProductDefinition
- Bundle
- Composition
- Ingredient
- Organization
- RegulatedAuthorization
- SubstanceDefinition
3. Set up the storage account and set the connection string in the FHIR server config
4. Run the export by calling url: `'<fhir server url>/$export?_container=$containerName&_since='$YesterdayDate&_till=$CurrentDate&_type=MedicinalProductDefinition,Bundle,Composition,Ingredient,Organization,RegulatedAuthorization,SubstanceDefinition'

**Expected behavior**
The export job finishes with success

**Actual behavior**
The export job fails and throws System.OutOfMemoryException

[AB#117698](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/117698)

**Comment by mikaelweave** [comment]
Hi @rafalbroll-datapharm, I think this behavior is expected. `$export` currently needs memory to serialize the data it is writing to Azure Storage. I would suggest one of the following actions to resolve your issue:

- Run your FHIR Server on compute with more memory. Try 4GB or 8GB and see if the `$export` operation completes with more memory.
- Reduce the number of resources exported by a single job
  - You can use the `_maxCount=xxxx` query parameter or set `MaximumNumberOfResourcesPerQuery` in the export configuration section.
  - The default is 10,000 - if you don't want to increase the size of your compute you could try 5,000.

Thanks for the issue, let me know if the above helps.

**Comment by rafalbroll-datapharm** [comment]
Thank you so much @mikaelweave! It solves the issue :)

I've run some tests to determine the optimal value for 3.5 GB of RAM. Setting the MaximumNumberOfResourcesPerQuery to 100 is very safe but then the operation takes too much time. Setting to 2000 was still causing the exception. I ended up at the value 1000 and it's perfectly fine.

Perhaps it's worth considering to add this param in the documentation here? https://github.com/microsoft/fhir-server/blob/main/docs/BulkExport.md
