### ISSUE TITLE
Using sql, posting a resource with a search url reference returns 500

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#788]
**Describe the bug**
When posting a resource to a SQL backed server that has a reference like the one found below, the server returns a `500` response code

```json
"subject": {
    "reference": "Patient?identifier=2fa15bc7-8866-461a-9000-f739e425860b"
  }
```

**To Reproduce**
1. Post an observation like this one to the `/Observation` route

```json
{
  "resourceType": "Observation",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: example</p><p><b>status</b>: final</p><p><b>category</b>: Vital Signs <span>(Details : {http://hl7.org/fhir/observation-category code 'vital-signs' = 'Vital Signs', given as 'Vital Signs'})</span></p><p><b>code</b>: Body Weight <span>(Details : {LOINC code '29463-7' = 'Body weight', given as 'Body Weight'}; {LOINC code '3141-9' = 'Body weight Measured', given as 'Body weight Measured'}; {SNOMED CT code '27113001' = 'Body weight', given as 'Body weight'}; {http://acme.org/devices/clinical-codes code 'body-weight' = 'body-weight', given as 'Body Weight'})</span></p><p><b>subject</b>: <a>Patient/example</a></p><p><b>context</b>: <a>Encounter/example</a></p><p><b>effective</b>: 28/03/2016</p><p><b>value</b>: 185 lbs<span> (Details: UCUM code [lb_av] = 'lb_av')</span></p></div>"
  },
  "status": "final",
  "category": [
    {
      "coding": [
        {
          "system": "http://hl7.org/fhir/observation-category",
          "code": "vital-signs",
          "display": "Vital Signs"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "29463-7",
        "display": "Body Weight"
      },
      {
        "system": "http://loinc.org",
        "code": "3141-9",
        "display": "Body weight Measured"
      },
      {
        "system": "http://snomed.info/sct",
        "code": "27113001",
        "display": "Body weight"
      },
      {
        "system": "http://acme.org/devices/clinical-codes",
        "code": "body-weight",
        "display": "Body Weight"
      }
    ]
  },
  "subject": {
    "reference": "Patient?identifier=2fa15bc7-8866-461a-9000-f739e425860b"
  },
  "context": {
    "reference": "Encounter/example"
  },
  "effectiveDateTime": "2016-03-28",
  "valueQuantity": {
    "value": 185,
    "unit": "lbs",
    "system": "http://unitsofmeasure.org",
    "code": "[lb_av]"
  }
}
```

**Expected behavior**
Currently, the CosmosDB provider persists the resource with the reference intact. We should investigate if this is valid per the spec and if so do the same thing in SQL server. 

**Actual behavior**
The server returns an operation outcome with the status code `500`.

**Stack trace**
```
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Health.Fhir.SqlServer.Features.Storage.TvpRowGeneration.ReferenceSearchParameterRowGenerator.TryGenerateRow(Int16 searchParamId, ReferenceSearchValue searchValue, ReferenceSearchParamTableTypeRow& row) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\TvpRowGeneration\ReferenceSearchParameterRowGenerator.cs:line 20
   at Microsoft.Health.Fhir.SqlServer.Features.Storage.TvpRowGeneration.SearchParameterRowGenerator`2.GenerateRows(ResourceMetadata input)+MoveNext() in C:\projects\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\TvpRowGeneration\SearchParameterRowGenerator.cs:line 41
   at Microsoft.Health.Fhir.SqlServer.EnumerableExtensions.NullIfEmpty[T](IEnumerable`1 enumerable) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.SqlServer\EnumerableExtensions.cs:line 28
   at Microsoft.Health.Fhir.SqlServer.Features.Schema.Model.TableValuedParameterDefinition`1.AddParameter(SqlParameterCollection parameters, IEnumerable`1 value) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Model\TableValuedParameterDefinition.cs:line 45
   at Microsoft.Health.Fhir.SqlServer.Features.Schema.Model.V1.UpsertResourceProcedure.PopulateCommand(SqlCommand command, Int64 baseResourceSurrogateId, Int16 resourceTypeId, String resourceId, Nullable`1 eTag, Boolean allowCreate, Boolean isDeleted, Boolean keepHistory, String requestMethod, Stream rawResource, IEnumerable`1 resourceWriteClaims, IEnumerable`1 compartmentAssignments, IEnumerable`1 referenceSearchParams, IEnumerable`1 tokenSearchParams, IEnumerable`1 tokenTextSearchParams, IEnumerable`1 stringSearchParams, IEnumerable`1 numberSearchParams, IEnumerable`1 quantitySearchParams, IEnumerable`1 uriSearchParams, IEnumerable`1 dateTimeSearchParms, IEnumerable`1 referenceTokenCompositeSearchParams, IEnumerable`1 tokenTokenCompositeSearchParams, IEnumerable`1 tokenDateTimeCompositeSearchParams, IEnumerable`1 tokenQuantityCompositeSearchParams, IEnumerable`1 tokenStringCompositeSearchParams, IEnumerable`1 tokenNumberNumberCompositeSearchParams) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Model\V1.Generated.cs:line 471
   at Microsoft.Health.Fhir.SqlServer.Features.Schema.Model.V1.UpsertResourceProcedure.PopulateCommand(SqlCommand command, Int64 baseResourceSurrogateId, Int16 resourceTypeId, String resourceId, Nullable`1 eTag, Boolean allowCreate, Boolean isDeleted, Boolean keepHistory, String requestMethod, Stream rawResource, UpsertResourceTableValuedParameters tableValuedParameters) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Model\V1.Generated.cs:line 489
   at Microsoft.Health.Fhir.SqlServer.Features.Storage.SqlServerFhirDataStore.UpsertAsync(ResourceWrapper resource, WeakETag weakETag, Boolean allowCreate, Boolean keepHistory, CancellationToken cancellationToken) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\SqlServerFhirDataStore.cs:line 104
   at Microsoft.Health.Fhir.Core.Features.Resources.Create.CreateResourceHandler.Handle(CreateResourceRequest message, CancellationToken cancellationToken) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Resources\Create\CreateResourceHandler.cs:line 45
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Microsoft.Health.Fhir.Core.Extensions.FhirMediatorExtensions.CreateResourceAsync(IMediator mediator, ResourceElement resource, CancellationToken cancellationToken) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Extensions\FhirMediatorExtensions.cs:line 31
   at Microsoft.Health.Fhir.Api.Controllers.FhirController.Create(Resource resource) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.Shared.Api\Controllers\FhirController.cs:line 153
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 63
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.PublishNotificationAsync(HttpContext context, RequestDelegate next) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 90
   at Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.Api\Features\ApiNotifications\ApiNotificationMiddleware.cs:line 52
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Health.Fhir.Api.Features.Audit.AuditMiddleware.Invoke(HttpContext context) in C:\projects\fhir-server\src\Microsoft.Health.Fhir.Api\Features\Audit\AuditMiddleware.cs:line 41
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by CaitlinV39** [comment]
@rbans96 is there additional work on this needed or is it complete?

**Comment by rbans96** [comment]
> @rbans96 is there additional work on this needed or is it complete

Completed.
