### ISSUE TITLE
404 from hapi-fhir-cli when uploading terminology

### ISSUE THREAD

**Issue by lrasmus** [microsoft/fhir-server#809]
**Describe the bug**
The hapi-fhir-cli receives a 404 response from fhir-server when attempting to upload LOINC or SNOMED terminologies.

**To Reproduce**
1. Build hapi-fhir-cli from source or download from latest release
2. Download LOINC from LOINC website or SNOMED-CT from NLM website
3. Build latest fhir-server locally (running on macOS 10.13, but have replicated when [deploying to Azure as well](https://github.com/microsoft/fhir-server/blob/master/docs/DefaultDeployment.md#deploying-the-fhir-server-template))
3. Run terminology upload command.  e.g. `hapi-fhir-cli upload-terminology -v r4 -t http://localhost:5000/ -u http://loinc.org -d ./config/Loinc_2.67.zip`

**Expected behavior**
The terminology should be loaded into the database (_iff the upload mechanism hapi-fhir-cli uses is standard compliant and should be supported_)

**Actual behavior**
Receive the following error message from hapir-fhir-cli

```
------------------------------------------------------------
🔥  HAPI FHIR 4.2.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 86632@MBP
Max configured JVM memory (Xmx) : 8.0GB
Detected Java version           : 11.0.4
------------------------------------------------------------
2020-01-09 11:02:52.111 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: ./config/Loinc_2.67.zip
2020-01-09 11:02:53.746 [main] INFO  c.u.f.c.UploadTerminologyCommand File size is greater than 10 MB - Going to use a local file reference instead of a direct HTTP transfer. Note that this will only work when executing this command on the same server as the FHIR server itself.
2020-01-09 11:02:54.492 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2020-01-09 11:02:55.09 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "id": "3751eab3-fc15-4659-a94f-23a2790c5a93",
  "issue": [
    {
      "severity": "error",
      "code": "not-found",
      "diagnostics": "The requested route was not found."
    }
  ]
}
2020-01-09 11:02:55.11 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HTTP 404 Not Found: The requested route was not found.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:434)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1173)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:204)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:113)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:251)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2020-01-09 11:02:55.11 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...

```

When enabling Debug messages in fhir-server, I see the following.  Seems like it could be related to `POST requests are not supported`?

```
info: Microsoft.Health.Fhir.Api.Features.ApiNotifications.ApiNotificationMiddleware[0]
      ApiNotificationMiddleware executed in 00:00:01.5057269.
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HLSK8KOMRKK5" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1565.4897ms 200 application/fhir+xml; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/CodeSystem/$upload-external-code-system application/fhir+json; charset=UTF-8 665
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[1]
      POST requests are not supported
dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
      Request successfully matched the route with name '(null)' and template '{typeParameter:fhirResource}/{idParameter}'
dbug: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
      Action 'Microsoft.Health.Fhir.Api.Controllers.FhirController.Update (Microsoft.Health.Fhir.R4.Api)' with id '4ff61d52-ddc5-4d26-a6ac-89e5e7812f23' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
dbug: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
      Action 'Microsoft.Health.Fhir.Api.Controllers.FhirController.Read (Microsoft.Health.Fhir.R4.Api)' with id 'c93d7dab-3329-43eb-b7da-03adfbb8b6eb' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
dbug: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
      Action 'Microsoft.Health.Fhir.Api.Controllers.FhirController.Delete (Microsoft.Health.Fhir.R4.Api)' with id 'a58dcdd5-3404-4193-9148-14aa0e523a33' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
dbug: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
      Action 'Microsoft.Health.Fhir.Api.Controllers.FhirController.Patch (Microsoft.Health.Fhir.R4.Api)' with id '94bdfb51-9970-4f5c-b93c-f70e818cf08e' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
dbug: Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler[3]
      No actions matched the current request. Route values: typeParameter=CodeSystem, idParameter=$upload-external-code-system
dbug: Microsoft.AspNetCore.Builder.RouterMiddleware[1]
      Request did not match any routes
```

**Comment by lrasmus** [comment]
Looking at some examples further, I can see that in the conformance statement from fhir-server does not specify that it supports `$upload-external-code-system`, so my expected behavior should not actually be expected.
